cairo_resource_fee_weights:
  n_steps: 1.0
compiled_class_hash_commitment_tree_height: 251
contract_storage_commitment_tree_height: 251
enforce_l1_handler_fee: true
event_commitment_tree_height: 64
global_state_commitment_tree_height: 251
invoke_tx_max_n_steps: 1000000
min_gas_price: 100000000000
sequencer_address: '0x5ce143edbf39a5e450d0bdf68f4e6b515405d1e9ab89329efa75fd8a31d9487'
starknet_os_config:
  chain_id: 1536727068981429685321 # StarknetChainId.TESTNET.value
  fee_token_address: '0x213bf49565022d1b9863f122f9047d4a66322981700b4223f920b55f9348948'
tx_commitment_tree_height: 64
tx_version: 1
validate_max_n_steps: 1000000
