#!/bin/sh

set -e

STAGED_FILES=$(git diff --name-only --cached)
STAGED_FILES_FOR_FORMAT=$(./scripts/get_code_check_paths.sh format | xargs git diff --name-only --staged)
STAGED_FILES_FOR_LINT=$(./scripts/get_code_check_paths.sh lint | xargs git diff --name-only --staged)

if [ -z "${STAGED_FILES}" ]; then
  echo "pre-commit hook: no staged files, exiting";
  exit 0;
fi

poetry run poe type_check $STAGED_FILES

if [ ! -z "${STAGED_FILES_FOR_FORMAT}" ]; then
  poetry run poe format_check_selected $STAGED_FILES_FOR_FORMAT
fi

if [ ! -z "${STAGED_FILES_FOR_LINT}" ]; then
  poetry run poe lint_selected $STAGED_FILES_FOR_LINT
fi

