["protostar.config"]
protostar_version = "0.1.0"

["protostar.project"]
libs_path = "./lib"

["protostar.contracts"]
main = [
  "./src/main.cairo",
]

["protostar.build"]
disable_hint_validation = true
