["protostar.general"]
name = "testproj"
description = "descr"
license = "MIT"
version = "1.0"
authors = [
    "tomekgsd@gmail.com",
]
libs_path = "lib"

["protostar.contracts"]
main = [
    "src/main.cairo",
]
