
[protostar.shared_command_configs]
arg = "a"
shared_arg = true

[profile.testnet.protostar.shared_command_configs]
arg = "b"
shared_profiled_arg = true

[protostar.deploy]
arg = "c"
cmd_arg = true

[profile.testnet.protostar.deploy]
arg = "d"
