/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  legacy: [
    {
      type: 'autogenerated',
      dirName: 'legacy',
    },
  ],
  cairo1 : [
    {
      type: 'autogenerated',
      dirName: 'cairo-1',
    },
  ]
}

module.exports = sidebars
