# .github/workflows/auto-author-assign.yml
name: Auto Author Assign

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  assign-author:
    runs-on: ubuntu-20.04
    if: ${{ github.repository == 'software-mansion/protostar' }} # do not run on forks
    steps:
      - uses: toshimaru/auto-author-assign@v1.6.0