name: size-label
on: pull_request
jobs:
  size-label:
    runs-on: ubuntu-latest
    steps:
      - name: size-label
        uses: "pascalgn/size-label-action@v0.4.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          sizes: >
            {
              "0": "size/XS",
              "10": "size/S",
              "100": "size/M",
              "300": "size/L",
              "600": "size/XL",
              "1000": "size/XXL"
            }
