name: Build binaries

# TODO: Uncomment, when pushed to master. This will enable running workflow on new tags
#on:
#  push:
#    tags:
#      - '*'

on: [pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, macOS-10.15 ]  # TODO: Fix windows gmp.h not found issue, and add a windows binary
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Build binary
        run: |
          poetry run pyinstaller protostar.spec
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: protostar-${{ github.ref }}-${{ runner.os }}
          path: dist
  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
        - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

        - name: Create a Release
          uses: elgohr/Github-Release-Action@master
          env:
            GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          with:
            args: ${{ github.ref }}

        - name: Upload binaries to release
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: dist/*
            tag: ${{ github.ref }}
            overwrite: true
            file_glob: true
