name: Builds on MacOS
on:
  pull_request:
  workflow_dispatch:

jobs:
  build-on-mac:
    name: Builds on MacOS
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.14
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.14

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Build binary
        run: |
          poetry run poe build