name: Build binaries

on: [pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2019, ubuntu-20.04, macOS-10.15 ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Build binary
        run: |
          poetry run pyinstaller protostar.spec
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: protostar-${{ github.RUNNER_OS }}
          path: dist/protostar
