name: Build binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]  # TODO: Fix windows gmp.h not found issue, and add a windows binary
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Build binary
        run: |
          poetry run pyinstaller protostar.spec

      - name: Pack binary into a tarball
        run: tar -czvf protostar.tar.gz ./dist/protostar

      - name: Upload the tarball
        uses: actions/upload-artifact@v2
        with:
          name: protostar-${{ runner.os }}
          path: protostar.tar.gz
  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: dist

      - name: Upload macOS binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/protostar-macOS/protostar.tar.gz
          asset_name: protostar-macOS.tar.gz
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload Linux binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/protostar-Linux/protostar.tar.gz
          asset_name: protostar-Linux.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
