name: Builds on MacOS
on:
  pull_request:
  workflow_dispatch:
jobs:
  build-on-mac:
    name: Builds on MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.14
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.14

      - name: Setup package manager
        run: |
          python -m pip install --upgrade pip
          pip install poetry==1.3.2
          poetry config virtualenvs.create false
          
      - name: Install project dependencies
        run: |
          poetry export -o requirements.txt
          pip install -r requirements.txt
          poetry install
      - name: Install cairo bindings
        run: |
          poetry run ./scripts/install_cairo_bindings.sh
          
      - name: Build binary
        run: |
          poetry run poe build
