name: Test docs

on:
  pull_request:
    branches:
      - master
  merge_group:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-deploy:
    name: Test build docs
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./website
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: website/yarn.lock
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test build website
        run: yarn build