name: types -> format -> lint -> test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Check types
        run: |
          poetry run poe type_check
      - name: Check formatting with black
        run: |
          poetry run poe format_check
      - name: Analyzing the code with pylint
        run: |
          poetry run poe lint
      - name: Unit test
        run: |
          poetry run poe test
      - name: Convert coverage to XML
        run: |
          poetry run python -m coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
