name: Test installation process

on:
  push:
    branches: [master]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-10.15] # TODO: Fix windows gmp.h not found issue, and add a windows binary
    steps:
      - uses: actions/checkout@v2
      - name: Install protostar
        run: |
          curl -L https://raw.githubusercontent.com/software-mansion/protostar/master/install.sh | bash

      - name: Update env variables
        run: |
          source /home/runner/.bashrc | bash

      - name: Verify protostar is available from console
        run: |
          protostar --help | bash
